version: '3'
services:
  fulcrum1:
    build:
      context: ./Fulcrum
      dockerfile: Dockerfile.Fulcrum
      args:
        fulcrum2_server: dist066.inf.santiago.usm.cl
        fulcrum2_port: 50052
        fulcrum3_server: dist067.inf.santiago.usm.cl
        fulcrum3_port: 50053
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Fulcrum:/app/Fulcrum
    network_mode: "host"

  fulcrum2:
    build:
      context: ./Fulcrum
      dockerfile: Dockerfile.Fulcrum
      args:
        fulcrum1_server: dist065.inf.santiago.usm.cl
        fulcrum1_port: 50051
        fulcrum3_server: dist067.inf.santiago.usm.cl
        fulcrum3_port: 50053
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Fulcrum:/app/Fulcrum
    network_mode: "host"

  fulcrum3:
    build:
      context: ./Fulcrum
      dockerfile: Dockerfile.Fulcrum
      args:
        fulcrum1_server: dist065.inf.santiago.usm.cl
        fulcrum1_port: 50051
        fulcrum2_server: dist066.inf.santiago.usm.cl
        fulcrum2_port: 50052
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Fulcrum:/app/Fulcrum
    network_mode: "host"

  informante1:
    build:
      context: ./Informantes
      dockerfile: Dockerfile.Informante
      args:
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50080
    volumes:
      - ./Informante:/app/Informante
    network_mode: "host"

  informante2:
    build:
      context: ./Informantes
      dockerfile: Dockerfile.Informante
      args:
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50080
    volumes:
      - ./Informante:/app/Informante
    network_mode: "host"

  broker-luna:
    build:
      context: ./BrokerLuna
      dockerfile: Dockerfile.BrokerLuna
      args:
        fulcrum1_server: dist065.inf.santiago.usm.cl
        fulcrum1_port: 50051
        fulcrum2_server: dist066.inf.santiago.usm.cl
        fulcrum2_port: 50052
        fulcrum3_server: dist067.inf.santiago.usm.cl
        fulcrum3_port: 50053
        informante1_server: dist065.inf.santiago.usm.cl
        informante1_port: 50081
        informante2_server: dist066.inf.santiago.usm.cl
        informante2_port: 50082
    volumes:
      - ./BrokerLuna:/app/BrokerLuna
    network_mode: "host"

  vanguardia:
    build:
      context: ./Vanguardia
      dockerfile: Dockerfile.Vanguardia
      args:
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50080
    volumes:
      - ./Vanguardia:/app/Vanguardia
    network_mode: "host"
