version: '3'
services:
  fulcrum1:
    build:
      context: ./Fulcrum
      dockerfile: Dockerfile.Fulcrum
      args:
        fulcrum1_server: dist065.inf.santiago.usm.cl
        fulcrum1_port: 50051
        fulcrum2_server: dist066.inf.santiago.usm.cl
        fulcrum2_port: 50052
        fulcrum3_server: dist067.inf.santiago.usm.cl
        fulcrum3_port: 50053
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Fulcrum:/app/Fulcrum
    network_mode: "host"

  informante:
    build:
      context: ./Informantes
      dockerfile: Dockerfile.Informantes
      args:
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Informantes:/app/Informantes
    network_mode: "host"

  broker-luna:
    build:
      context: ./BrokerLuna
      dockerfile: Dockerfile.BrokerLuna
      args:
        fulcrum1_server: dist065.inf.santiago.usm.cl
        fulcrum1_port: 50051
        fulcrum2_server: dist066.inf.santiago.usm.cl
        fulcrum2_port: 50052
        fulcrum3_server: dist067.inf.santiago.usm.cl
        fulcrum3_port: 50053
        informante1_server: dist065.inf.santiago.usm.cl
        informante1_port: 50081
        informante2_server: dist066.inf.santiago.usm.cl
        informante2_port: 50082
        vanguardia_server: dist067.inf.santiago.usm.cl
        vanguardia_port: 50083
    volumes:
      - ./BrokerLuna:/app/BrokerLuna
    network_mode: "host"

  vanguardia:
    build:
      context: ./Vanguardia
      dockerfile: Dockerfile.Vanguardia
      args:
        broker_server: dist068.inf.santiago.usm.cl
        broker_port: 50070
    volumes:
      - ./Vanguardia:/app/Vanguardia
    network_mode: "host"
